rules:
  - id: sql-injection-fstring
    pattern: |
      $DB.execute($QUERY, ...)
    pattern-not: |
      $DB.execute($QUERY, ($X,), ...)
    message: "SQL Injection: query pode estar vulneravel"
    languages: [python]
    severity: ERROR

  - id: xss-sem-escape
    patterns:
      - pattern: |
          def $FUNC($NAME):
              return f"<p>Ola, {$NAME}!</p>"
    message: "XSS: variavel inserida em HTML sem escape"
    languages: [python]
    severity: ERROR